apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-existing-storage
  labels:
    type: storage
    code: '210'
  annotations:
    displayName: Existing Storage
    description: Existing cluster storage either through native storage options or a previously installed ODF or Portworx instance
    dependencies.cloudnativetoolkit.dev/provides: storage
spec:
  version: v1.0.0
  modules:
    - name: util-storage-class-manager
