apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 165-ibm-fs-openshift-workload
  labels:
    type: infrastructure
    platform: ibm
    code: '165'
  annotations:
    displayName: OpenShift Workload
    description: Configures workload cluster
    vpn/required: "true"
    destroy/ignore-error: "true"
spec:
  modules:
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
        - name: resource_group_name
          alias: workload_resource_group_name
          scope: global
    - name: ibm-ocp-vpc
      dependencies:
        - name: subnets
          optional: true
        - name: cos
          optional: true
        - name: vpc
          optional: true
      variables:
        - name: exists
          value: true
        - name: name
          required: true
        - name: vpc_subnet_count
          value: 0
        - name: vpc_subnets
          value: "[]"
        - name: cos_id
          value: ""
        - name: vpc_name
          value: ""
        - name: login
          value: true
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
    - name: namespace
      alias: tools_namespace
      default: true
      variables:
        - name: name
          value: tools
    - name: namespace
      alias: openshift-gitops
      variables:
        - name: name
          value: openshift-gitops
    - name: ibm-image-registry
      variables:
        - name: registry_namespace
          required: true
          scope: global
    - name: cluster-config
      variables:
        - name: banner_text
          value: Workload
        - name: banner_background_color
          value: red
    - name: openshift-cicd
  variables:
    - name: resource_group_name
    - name: region
    - name: ibmcloud_api_key
      required: true
    - name: registry_namespace
      required: true
    - name: name_prefix
      required: true
      alias: workload_name_prefix
    - name: tools_name
      value: tools
    - name: sealed-secret_name
      value: sealed-secrets
