apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: cp-data-fabric
  labels:
    code: '600'
  annotations:
    displayName: Data Fabric Solution on Cloud pak for Data
    description: GitOps deployment of Data Fabric Solution on Cloud pak for Data
spec:
  modules:
    # Login to OpenShift cluster
    - name: ocp-login
    - name: olm
    - name: sealed-secret-cert
    # Create the GitOps Repo
    - name: gitops-repo
    # Install ArgoCD
    - name: argocd-bootstrap


    # Namespaces for Common/Foundational Services, CP4D Operators and CP4D Platform instance & Services
    - name: gitops-namespace
      variables:
        - name: cs-namespace
          value: ibm-common-services 
        - name: operator_namespace
          value: cpd-operators   
        - name: cpd_namespace
          value: gitops-cp4d-instance  

    - name: gitops-pull-secret  # Global pull secret is required. This is temprary
      dependencies:
        - name: cs-namespace
          ref: ibm-common-services
        - name: operator_namespace
          ref: cpd-operators 
        - name: cpd_namespace
          ref: gitops-cp4d-instance 

    # CatalogSources ibm-operator-catalog & ibm-db2uoperator-catalog
    - name: gitops-cp-catalogs
      dependencies:
        - name: cs-namespace
          ref: ibm-common-services

    # CP4D platform Foundational Services
    - name: ibm-common-service
      dependencies:
        - name: cs-namespace
          ref: ibm-common-services  

    # CP4D Operator
    - name: gitops-cp4d-operator
      dependencies:
        - name: operator_namespace
          ref: cpd-operators 

    # CP4D Instance
    - name: cp4d-instance
      dependencies:
        - name: cpd_namespace
          ref: gitops-cp4d-instance
      variables:
        - name: storage_vendor
          value: portworx

    # Watson Knowledge Catalog
    - name: gitops-cp-watson-knowledge-catalog
      dependencies:
        - name: operator_namespace
          ref: cpd-operators 
        - name: cpd_namespace
          ref: gitops-cp4d-instance   
      variables:
        - name: storage_vendor
          value: portworx
    
    # Watson Studio
    - name: gitops-cp-watson-studio
      dependencies:
        - name: operator_namespace
          ref: cpd-operators 
        - name: cpd_namespace
          ref: gitops-cp4d-instance   
      variables:
        - name: storage_vendor
          value: portworx
        - name: storageclass
          value: portworx-shared-gp3 

    # Watson Machine Learning
    - name: gitops-cp-watson-machine-learning
      dependencies:
        - name: operator_namespace
          ref: cpd-operators 
        - name: cpd_namespace
          ref: gitops-cp4d-instance   
      variables:
        - name: storageclass
          value: portworx-shared-gp3 
    
    # Data Virtualization Service
    - name: gitops-cp-data-virtualization-service
      dependencies:
        - name: operator_namespace
          ref: cpd-operators 
        - name: cpd_namespace
          ref: gitops-cp4d-instance  
    
    # Provision Data Virtualization
    - name: gitops-cp-data-virtualization
      dependencies:
        - name: operator_namespace
          ref: cpd-operators 
        - name: cpd_namespace
          ref: gitops-cp4d-instance 
      variables:
        - name: storageclass
          value: portworx-db2-rwx-sc
    
    # Create AWS S3 Bucket instance
    - name: aws-s3-instance
      variables:
        - name: bucket_prefix
          value: datafabric
        - name: region
          value: ap-south-1

    # Upload Data files to AWS S3 Bucket
    - name: aws-s3-bucket
      variables:
        - name: file_path
          value: Datafiles/aws/ 

    # Data Fabric Configuration & Setup
    - name: gitops-cp-data-fabric
      variables:
        - name: cpd_namespace
          value: gitops-cp4d-instance
        - name: bucket_id
          value: dfabbucket
        - name: region
          value: ap-south-1

    