apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 610-datafabric-demo
  labels:
    type: software
    code: '610'
  annotations:
    displayName: Data Fabric - Demo Solution
    description: GitOps deployment of Data Fabric Sample for Cloud pak for Data
spec:
  modules:

    - name: gitops-namespace
      alias: ibm_common_services_namespace
      variables:
        - name: name
          value: ibm-common-services

    - name: gitops-namespace
      alias: cpd_operators_namespace
      variables:
        - name: name
          value: cpd-operators

    - name: gitops-namespace
      alias: cp4d_namespace
      variables:
        - name: name
          value: cp4d

    # Create AWS S3 Bucket instance
    - name: aws-s3-instance
      variables:
        - name: bucket_prefix
          value: datafabric
        - name: region
          scope: global

    # Upload Data files to AWS S3 Bucket
    - name: aws-s3-bucket
      variables:
        - name: file_path
          value: Datafiles/aws/

    # Data Fabric Configuration & Setup
    - name: gitops-cp-data-fabric
      dependencies:
        - name: namespace
          ref: data_fabric_namespace
      variables:
        - name: cpd_namespace
          value: cp4d_namespace
        - name: bucket_id
          value: dfabbucket
        - name: s3_bucket_region
          alias: region
          scope: global

  varables:
    - name: cp
      value: cp
    - name: region
      value: ap-south-1
