apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 105-aws-vpc-openshift
  labels:
    type: infrastructure
    platform: aws
    code: '105'
  annotations:
    displayName: AWS VPC OpenShift
    description: AWS VPC and Red Hat OpenShift servers
spec:
  modules:
    - name: aws-vpc
    - name: aws-internet-gateway
      alias: internet_gateway
    - name: aws-nat-gateway
      alias: nat_gateway
      dependencies:
        - name: aws-vpc-subnets
          ref: public_subnets
    - name: aws-vpc-subnets
      alias: public_subnets
      dependencies:
        - name: gateways
          ref: internet_gateway
    - name: aws-vpc-subnets
      alias: private_subnets
      dependencies:
        - name: gateways
          ref: nat_gateway
    - name: aws-rosa
      dependencies:
        - name: public-subnets
          ref: public_subnets
        - name: private-subnets
          ref: private_subnets
