apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-ibm-odf-storage
  labels:
    type: infrastructure
    platform: ibm
    code: '210'
  annotations:
    displayName: IBM - ODF Cluster Storage
    description: Installs OpenShift Data Foundation in an IBM cluster
spec:
  modules:
    # Create the GitOps Repo
    - name: gitops-repo
    - name: gitops-namespace
      alias: odf_namespace
      default: true
    - name: gitops-ibm-odf
      variables:
        - name: cluster_name
          scope: global
