apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: new-gitops-testing-cluster
  labels:
    platform: ibm
  annotations:
    displayName: New OpenShift Cluster
    description: OpenShift Cluster on IBM Cloud with Portworx
spec:
  modules:
    - name: ibm-resource-group
      alias: resource_group
      variables:
        - name: provision
          value: false
          
    - name: ibm-vpc

    - name: ibm-vpc-subnets
      alias: vpc-subnets

    - name: ibm-vpc-vpn-gateway
      dependencies:
        - name: subnets
          ref: vpc-subnets

    - name: ibm-ocp-vpc
      dependencies:
        - name: subnets
          ref: vpc-subnets
        - name: vpc 
          ref: ibm-vpc
        - name: name_prefix
          scope: global
      variables:
        - name: ocp_version
          value: 4.8


    - name: logdna
      variables:
        - name: provision
          value: true
        - name: name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: resource_group
    - name: sysdig
      variables:
        - name: provision
          value: true
        - name: name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: resource_group
    - name: ibm-logdna-bind
    - name: sysdig-bind

    - name: ibm-portworx
      dependencies:
        - name: ibm-ocp-vpc
      variables:
        - name: provision
          value: false
  variables:
    - name: config_banner_text