apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 215-portworx-storage
  labels:
    type: infrastructure
  annotations:
    displayName: AWS - Portworx Cluster Storage
    description: Installs Portworx in and OCP cluster on AWS
spec:
  modules:
    - name: aws-portworx

