apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 400-mas-core-multicloud
  labels:
    type: software
    code: '400'
  annotations:
    displayName: Maximo Application Suite Core
    description: GitOps deployment of Maximo Application Suite Core for OpenShift
spec:
  modules:
    - name: gitops-repo

    # Add IBM OpenShift Catalog
    - name: gitops-cp-catalogs
      version: v1.2.1
      variables:
        - name: entitlement_key
          scope: global

    # IBM Suite License Service
    - name: gitops-namespace
      alias: sls-namespace
      variables:
        - name: name
          value: ibm-sls
    - name: gitops-cp-sls
      dependencies:
        - name: namespace
          ref: sls-namespace
      variables:
        - name: cluster_ingress
          scope: global
        - name: entitlement_key
          scope: global

    # Storage Class Manager
    - name: util-storage-class-manager
      variables:
        - name: rwx_storage_class
          scope: global
        - name: rwo_storage_class
          scope: global
        - name: file_storage_class
          scope: global
        - name: block_storage_class
          scope: global

    # Mongo CE Operator
    - name: gitops-namespace
      alias: mongo-namespace
      variables:
        - name: name
          value: mongo
    - name: gitops-mongo-ce-operator
      dependencies:
        - name: namespace
          ref: mongo-namespace

    # Mongo CE Instance
    - name: gitops-mongo-ce
      dependencies:
        - name: namespace
          ref: mongo-namespace

    # IBM Behavior Analysis Service
    - name: gitops-namespace
      alias: bas-namespace
      variables:
        - name: name
          value: masbas
    - name: gitops-cp-bas
      dependencies:
        - name: namespace
          ref: bas-namespace

    # Maximo Core
    - name: gitops-cp-maximo
      variables:
        - name: instanceid
          ref: mas8
        - name: cluster_ingress
          scope: global
        - name: entitlement_key
          scope: global
