apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 400-mas-core
  labels:
    type: software
    code: '400'
  annotations:
    displayName: Maximo Application Suite Core
    description: GitOps deployment of Maximo Application Suite Core for OpenShift
spec:
  modules:
    - name: gitops-repo

    # Add IBM OpenShift Catalog
    - name: gitops-cp-catalogs
      variables:
        - name: entitlement_key
          scope: global

    # IBM Suite License Service
    - name: gitops-namespace
      alias: sls-namespace
      variables:
        - name: name
          value: sls
    - name: gitops-cp-sls
      dependencies:
        - name: namespace
          ref: sls-namespace
      variables:
        - name: cluster_ingress
          scope: global
        - name: entitlement_key
          scope: global

    # Mongo CE Operator
    - name: gitops-namespace
      alias: mongo-namespace
      variables:
        - name: name
          value: mongo
    - name: gitops-mongo-ce-operator
      dependencies:
        - name: namespace
          ref: mongo-namespace
      variables:
        - name: mongo_storageclass
          alias: rwo_storage_class
          scope: global

    # Mongo CE Instance
    - name: gitops-mongo-ce
      dependencies:
        - name: namespace
          ref: mongo-namespace
      variables:
        - name: storage_class_name
          alias: rwo_storage_class
          scope: global

    # IBM Behavior Analysis Service
    - name: gitops-namespace
      alias: bas-namespace
      variables:
        - name: name
          value: bas
    - name: gitops-cp-bas
      version: v1.0.1
      dependencies:
        - name: namespace
          ref: bas-namespace
      variables:
        - name: db_archive_storage_class
          alias: rwx_storage_class
          scope: global
        - name: postgres_storage_class
          alias: rwo_storage_class
          scope: global
        - name: kafka_storage_class
          alias: rwo_storage_class
          scope: global
        - name: zookeeper_storage_class
          alias: rwo_storage_class
          scope: global
        - name: default_storage_class
          alias: rwo_storage_class
          scope: global

    # Maximo Core
    - name: gitops-namespace
      alias: maximo-namespace
      variables:
        - name: name
          value: maximo
    - name: gitops-cp-maximo
      variables:
        - name: instanceid
          ref: mas8
        - name: cluster_ingress
          scope: global
        - name: entitlement_key
          scope: global
      dependencies:
        - name: namespace
          ref: maximo-namespace
