apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-azure-portworx-storage
  labels:
    type: software
    code: '210'
    platform: azure
  annotations:
    displayName: Azure - Portworx Cluster Storage
    description: Installs Portworx into an OCP cluster on Azure
spec:
  modules:
    - name: azure-portworx

