apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 130-ibm-zdev-development-vpc-openshift
  labels:
    type: infrastructure
    platform: ibm
    code: 130
  annotations:
    displayName: Development VPC OpenShift
    description: Devleopment VPC and Red Hat OpenShift servers
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
    - name: ibm-resource-group
      alias: at_resource_group
    - name: ibm-kms
      alias: kms
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ""
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: mgmt_resource_group_name
          scope: global
    - name: ibm-iam-service-authorization
      alias: flow-log-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: flow-log-collector
        - name: roles
          value:
            - Writer
      dependencies:
        - name: target_resource_group
          ref:  ibm-resource-group
        - name: target_resource
          ref: cos
    - name: ibm-access-group
    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.10.0.0/18
            - 10.20.0.0/18
            - 10.30.0.0/18
    - name: ibm-flow-logs
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: worker-subnets
      variables:
        - name: _count
          alias: mgmt_worker_subnet_count
          scope: global
          value: 3
        - name: label
          value: worker
        - name: ipv4_cidr_blocks
          value:
            - 10.10.10.0/24
            - 10.20.10.0/24
            - 10.30.10.0/24
        - name: acl_rules
          value:
            - {"name":"allow-vpn-ingress","action":"allow","direction":"inbound","source":"0.0.0.0/0", "destination":"10.0.0.0/8"}
            - {"name":"allow-vpn-egress","action":"allow","direction":"inbound","source":"10.0.0.0/8", "destination":"0.0.0.0/0"}
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-ocp-vpc
      alias: cluster
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
        - name: worker_count
          alias: mgmt_worker_count
        - name: ocp_version
          value: 4.8
      dependencies:
        - name: subnets
          ref: worker-subnets
        - name: kms_key
          ref: kms-key
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.10.20.0/24
            - 10.20.20.0/24
            - 10.30.20.0/24
    - name: ibm-vpc-subnets
      alias: ingress-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.10.30.0/24
            - 10.20.30.0/24
            - 10.30.30.0/24
    - name: ibm-vpc-vpn-gateway
      dependencies:
        - name: subnets
          ref: vpn-subnets
    - name: ibm-resource-group
      alias: cs_resource_group
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-kms-key
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-activity-tracker
      dependencies:
        - name: resource_group
          ref: at_resource_group
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    - name: ibm-vpe-gateway
      alias: vpe-cos
      dependencies:
        - name: resource
          ref: cos
        - name: subnets
          ref: vpe-subnets
        - name: sync
          ref: cluster
    - name: ibm-transit-gateway
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource-group
          ref: cs_resource_group
    - name: ibm-log-analysis
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-cloud-monitoring
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-log-analysis-bind
    - name: ibm-cloud-monitoring-bind
    - name: ibm-vpc-subnets
      alias: vsi-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: worker-vsi
        - name: ipv4_cidr_blocks
          value:
            - 10.10.40.0/24
            - 10.20.40.0/24
            - 10.30.40.0/24
        - name: acl_rules
          value:
            - {"name":"allow-vpn-ingress","action":"allow","direction":"inbound","source":"0.0.0.0/0", "destination":"10.0.0.0/8"}
            - {"name":"allow-vpn-egress","action":"allow","direction":"inbound","source":"10.0.0.0/8", "destination":"0.0.0.0/0"}
    - name: ibm-vpc-vsi
      variables:
        - name: image_name
          value: "ibm-zos-2-4-s390x-dev-test-wazi-1"
        - name: profile_name
          value: "mz2-2x16"
        - name: security_group_rules
          value:
            - { "name": "ingress-everything", "direction": "inbound", "remote": "0.0.0.0/0"}
            - { "name": "egress-everything", "direction": "outbound", "remote": "0.0.0.0/0" }
      dependencies:
        - name: subnets
          ref: vsi-subnets
        - name: vpcssh
          ref: dev_ssh_vsi
    - name: ibm-vpc-ssh
      alias: dev_ssh_vsi
      variables:
        - name: label
          value: zos-vsi
  variables:
    - name: mgmt_resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      alias: mgmt_name_prefix
      required: true
    - name: cs_resource_group_name
    - name: cs_name_prefix
    - name: worker_count
    - name: kms_service
    - name: dev_ssh_vsi_public_key
      value: ""
    - name: dev_ssh_vsi_private_key
      value: ""
    - name: dev_ssh_vsi_public_key_file
    - name: dev_ssh_vsi_private_key_file
