apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 110-azure-ocp-ipi
  labels:
    type: infrastructure
    platform: azure
    code: '110'
  annotations:
    displayName: Azure OpenShift IPI
    description: Azure OpenShift IPI with created VNet
spec:
  modules:
    - name: azure-ocp-ipi