apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 220-dev-tools
  labels:
    type: software
    code: '220'
  annotations:
    displayName: OpenShift development tools
    description: Provisions development tools in an OpenShift cluster
    deployment-type/gitops: "true"
    vpn/required: "true"
spec:
  modules:
    # Create the GitOps Repo
    - name: gitops-repo

    - name: gitops-namespace
      alias: tools_namespace
      default: true
      version: v1.12.2
      variables:
        - name: name
          value: tools

    - name: gitops-artifactory
    - name: gitops-dashboard
    - name: gitops-pact-broker
    - name: gitops-sonarqube
    - name: gitops-tekton-resources
#   - name: gitops-image-registry
    - name: gitops-swagger-editor
