apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 160-openshift-dev-tools
  labels:
    platform: ibm
    code: '160'
  annotations:
    displayName: OpenShift Developer Tools
    description: Open-Source collection of assets for application development on OpenShift
spec:
  modules:
    - name: gitops-repo
    - name: gitops-namespace
      variables:
        - name: name
          value: tools
    - name: gitops-cluster-config
      variables:
        - name: banner_text
          value: Management
    - name: gitops-dashboard
    - name: gitops-pact-broker
    - name: gitops-artifactory
    - name: gitops-sonarqube
    - name: gitops-tekton-resources
  variables: []
