apiVersion: cloudnativetoolkit.dev/v2
kind: Solution
metadata:
  name: infra-azure-standard
  labels:
    type: infrastructure
    platform: azure
    flavor: standard
  annotations:
    displayName: "Infrastructure: Azure Standard"
    description: A standard production deployment environment with typical security protections, private endpoints, VPN server, key management encryption, ideal for POC/POT/MVP
    files.cloudnativetoolkit.dev/diagram: diagram.png
spec:
  version: v1.1.0
  stack:
    - name: 101-azure-vnet-std
      layer: infrastructure
      description: Azure base infrastructure for OpenShift standard architecture
    - name: 105-azure-aro-std
      layer: infrastructure
      description: Azure ARO for Standard Architecture
    - name: 200-openshift-gitops
      layer: platform
      description: Provisions OpenShift GitOps into an existing OpenShift cluster and bootstraps it to a gitops repository
  variables:
    - name: gitops_repo_host
    - name: gitops_repo_username
    - name: gitops_repo_token
  files:
    - name: diagram.png
      type: image
      contentUrl: https://raw.githubusercontent.com/cloud-native-toolkit/automation-solutions/main/boms/infrastructure/azure/openshift-aro/2-standard/architecture.png
