apiVersion: cloudnativetoolkit.dev/v2
kind: Solution
metadata:
  name: infra-azure-quickstart
  labels:
    type: infrastructure
    platform: azure
    flavor: quickstart
  annotations:
    displayName: "Infrastructure: Azure Quickstart"
    description: Azure simple architecture to quickly get an OpenShift cluster provisioned, ideal for demos
    files.cloudnativetoolkit.dev/diagram: diagram.png
spec:
  version: v1.1.0
  stack:
    - name: 105-azure-aro
      layer: infrastructure
      description: Azure VPC and public Red Hat OpenShift cluster
    - name: 200-openshift-gitops
      layer: platform
      description: Provisions OpenShift GitOps into an existing OpenShift cluster and bootstraps it to a gitops repository
  variables:
    - name: gitops_repo_host
    - name: gitops_repo_username
    - name: gitops_repo_token
  files:
    - name: diagram.png
      type: image
      contentUrl: https://raw.githubusercontent.com/cloud-native-toolkit/automation-solutions/main/boms/infrastructure/azure/openshift-aro/1-quickstart/architecture.png
