apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 105-azure-ocp-ipi
  labels:
    type: infrastructure
    platform: azure
    code: '105'
  annotations:
    displayName: Azure OpenShift IPI
    description: Azure OpenShift Installer Provided Infrastructure
spec:
  version: v1.0.0
  modules:
    - name: azure-ocp-ipi
      variables:
        - name: region
          scope: global
        - name: name_prefix
          scope: global
        - name: client_id
          scope: global
        - name: client_secret
          scope: global
        - name: subscription_id
          scope: global
        - name: tenant_id
          scope: global
        - name: pull_secret
          scope: global