apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 305-cloud-pak-for-data-foundation
  labels:
    type: software
    code: '305'
  annotations:
    displayName: Data Foundation
    description: GitOps deployment of Data Foundation for Cloud pak for Data
    deployment-type/gitops: "true"
spec:
  modules:

    # Namespaces for Common/Foundational Services, CP4D Operators and CP4D Platform instance & Services
    - name: gitops-namespace
      alias: ibm_common_services_namespace
      variables:
        - name: name
          alias: ibm_common_services_namespace
          scope: global

    - name: gitops-namespace
      alias: cpd_operators_namespace
      variables:
        - name: name
          alias: cpd_operators_namespace
          scope: global

    - name: gitops-namespace
      alias: cp4d_namespace
      variables:
        - name: name
          alias: cp4d_namespace
          scope: global

    # CatalogSources ibm-operator-catalog & ibm-db2uoperator-catalog
    - name: gitops-cp-catalogs
      dependencies:
        - name: namespace
          ref: ibm_common_services_namespace
      variables:
        - name: entitlement_key
          scope: global

          #var.gitops-cp-catalogs_entitlement_key make it use global scope

    # CP4D platform Foundational Services
#    - name: ibm-common-service
#      dependencies:
#        - name: namespace
#          ref: ibm_common_services_namespace

    # CP4D Operator
    - name: gitops-cp4d-operator
      dependencies:
        - name: namespace
          ref: cpd_operators_namespace
        - name: ibm-common-service
          optional: true

    # CP4D Instance
    - name: cp4d-instance
      dependencies:
        - name: namespace
          ref: cp4d_namespace
      variables:
        - name: storage_vendor
          value: portworx

  variables:
    - name: ibm_common_services_namespace
      value: ibm-common-services
    - name: cpd_operators_namespace
      value: cpd-operators
    - name: cp4d_namespace
      value: cp4d