apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 310-cloud-pak-for-data-db2uoperator
  labels:
    type: software
    code: '310'
  annotations:
    displayName: DB2UOperator for Cloud Pak for Data
    description:  GitOps deployment of DB2U Operator for Cloud pak for Data
spec:
  modules:
    - name: gitops-namespace
      alias: gitops-db2u_namespace
      variables:
        - name: name
          value: gitops-db2u
        - name: operator_namespace
          value: cpd-operators
        - name: channel
          value: v1.1
        - name: subscription_source_namespace
          value: openshift-marketplace
    - name: gitops-db2u
      dependencies:
        - name: namespace
          ref: 	gitops-db2u_namespace
        - name: namespace
          optional: true
        - name: gitops-cp4d-instance
          optional: true
        - name: cp4d-instance
          optional: true
        - name: gitops-cp4d-operator
          optional: true
        - name: gitops-cp-catalogs
          optional: true
        - name: ibm-common-service
          optional: true
