apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 315-cloud-pak-for-data-db2wh
  labels:
    type: software
    code: '315'
  annotations:
    displayName: DB2 Warehouse for Cloud Pak for Data
    description:  GitOps deployment of DB2 Warehouse for Cloud pak for Data
    apply-all/optional: "true"
    deployment-type/gitops: "true"
spec:
  modules:
    - name: gitops-namespace
      alias: gitops-cp-db2wh_namespace
      variables:
        - name: name
          value: gitops-cp-db2wh
    - name: gitops-cp-db2wh
      variables:
        - name: common_services_namespace
          alias: ibm_common_services_namespace
          scope: global
        - name: operator_namespace
          alias: cpd_operators_namespace
          scope: global
        - name: cpd_namespace
          alias: cp4d_namespace
          scope: global
        - name: license
          value: Enterprise
        - name: db2_warehouse_channel
          value: v1.0
        - name: db2_warehouse_version
          value: 4.0.2 
        - name: namespace  
          value: gitops-cp-db2wh
        - name: storage_class
          value: portworx-shared-gp3
      dependencies:
        - name: namespace
          ref: gitops-cp-db2wh_namespace
        - name: namespace
          optional: true
        - name: gitops-cp4d-instance
          optional: true
        - name: cp4d-instance
          optional: true
        - name: gitops-cp4d-operator
          optional: true
        - name: gitops-cp-catalogs
          optional: true
        - name: ibm-common-service
          optional: true
  variables:
    - name: ibm_common_services_namespace
      value: ibm-common-services
    - name: cpd_operators_namespace
      value: cpd-operators
    - name: cp4d_namespace
      value: cp4d
