apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 320-cloud-pak-for-data-db2oltp
  labels:
    type: software
    code: '320'
  annotations:
    displayName: DB2 OLTP for Cloud Pak for Data
    description:  GitOps deployment of DB2 OLTP for Cloud pak for Data
    apply-all/optional: "true"
spec:
  modules:
    - name: gitops-namespace
      alias: gitops-cp-db2oltp_namespace
      version: v1.0.11
      variables:
        - name: name
          value: gitops-cp-db2oltp
    - name: gitops-db2-oltp
      variables:
        - name: common_services_namespace
          alias: ibm_common_services_namespace
          scope: global
        - name: operator_namespace
          alias: cpd_operators_namespace
          scope: global
        - name: cpd_namespace
          alias: cp4d_namespace
          scope: global
        - name: subscription_source_namespace
          value: openshift-marketplace
        - name: license
          value: Advanced
        - name: channel
          value: v1.0
        - name: namespace  
          value: gitops-cp-db2oltp
      dependencies:
        - name: namespace
          ref: gitops-cp-db2oltp_namespace
        - name: namespace
          optional: true
        - name: gitops-db2u
          optional: true
        - name: gitops-cp4d-instance
          optional: true
        - name: cp4d-instance
          optional: true
        - name: gitops-cp4d-operator
          optional: true
        - name: gitops-cp-catalogs
          optional: true
        - name: ibm-common-service
          optional: true
  variables:
    - name: ibm_common_services_namespace
      value: ibm-common-services
    - name: cpd_operators_namespace
      value: cpd-operators
    - name: cp4d_namespace
      value: cp4d
