apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 000-account-setup
  labels:
    type: infrastructure
    platform: ibm
    code: 000
  annotations:
    displayName: Account setup
    description: Sets up an IBM Cloud account with required Financial Services reference architecture settings
spec:
  modules:
    - name: ibm-resource-group
      alias: at_resource_group
      default: true
      variables:
        - name: provision
          value: false
    - name: ibm-activity-tracker
      alias: at-us-east
      variables:
        - name: resource_location
          value: "us-east"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-us-south
      variables:
        - name: resource_location
          value: "us-south"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-eu-de
      variables:
        - name: resource_location
          value: "eu-de"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-eu-gb
      variables:
        - name: resource_location
          value: "eu-gb"
          scope: module
        - name: provision
          value: true
  variables:
    - name: at_resource_group_provision
    - name: at_resource_group_name
    - name: name_prefix
      alias: common_name_prefix
    - name: region
