apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 110-aws-std-edge-vpc
spec:
  modules:
#edge VPC  
    - name: aws-vpc
      alias: edge_vpc
      variables:
      - name: internal_cidr
        value: 10.0.0.0/16        
#Edge Subnet - Public
    - name: aws-vpc-subnets
      alias: edge_bastion_pub_subnets
      dependencies:
        - name: gateways
          ref: edge-igw
      variables:
      - name: label
        value: public 
      - name: subnet_cidrs
        value:
          - 10.0.1.0/24
          - 10.0.2.0/24
          - 10.0.3.0/24
#Edge Subnet - Private
    - name: aws-vpc-subnets
      alias: edge_bastion_pri_subnets
      dependencies:
        - name: gateways
          ref: edge-nat
      variables:
      - name: label
        value: private
      - name: subnet_cidrs
        value:
          - 10.0.4.0/24
          - 10.0.5.0/24
          - 10.0.6.0/24  
#Internet Gateway
    - name: aws-internet-gateway
      alias: edge-igw
#NAT Gateway
    - name: aws-nat-gateway
      alias: edge-nat
      dependencies:
        - name: aws-vpc-subnets
          ref: edge_bastion_pri_subnets
      variables:
        - name : connectivity_type
          value: public   
        - name : _count
          value: 3

#KMS for encryption
    - name: aws-kms
      alias: storage_kms
      variables:
      - name: user_arn
        important: true
#SSH Key
    - name: aws-ssh-key
      alias: ec2_access_key
#Bastion Instance
    - name: aws-ec2-bastion
      dependencies:
        - name: aws-vpc-subnets
          ref: edge_bastion_pub_subnets
        - name: aws-ssh-key
        - name: aws-kms
      variables:
      - name: ami_id
        value: ami-08df646e18b182346
#VPN service
    - name: aws-client-vpn
      alias: edge-vpn
      dependencies:
        - name: aws-vpc-subnets
          ref: edge_bastion_pri_subnets
      variables:
      - name: number_subnets_association
        value: 3
      - name: client_cidr_block
        value: 172.13.0.0/16
        important: true
      - name: dns_servers
        value:
          - 10.0.0.2
        important: true          
      - name: allowed_cidr_ranges
        value:
          - 10.0.0.0/16    
        important: true                           
#Global Variables  
  variables:
    - name: name_prefix
      scope: global
      value: "aws-std"
      important: true            
    - name: resource_group_name
      scope: global
      value: "edge"       
    - name: provision
      value: true
      scope: global
    - name: region
      value: ap-south-1
      scope: global