apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: aws-standard-architecture
spec:
  modules:
# VPC
    - name: aws-vpc
      variables:
      - name: enable_dns_hostnames
        value: true
      dependencies:
        - name: aws-vpc-subnets
          ref: pri_subnets
        - name: aws-client-vpn
#Internet Gateway
    - name: aws-internet-gateway
      alias: igw
# Subnet for Bastion and ROSA - Public
    - name: aws-vpc-subnets
      alias: pub_subnets
      dependencies:
        - name: gateways
          ref: igw
      variables:
      - name: label
        value: public
      - name: subnet_cidrs
        alias: pub_subnet_cidrs
        value:
          - 10.0.1.0/24
          - 10.0.2.0/24
          - 10.0.3.0/24
      - name: availability_zones
        value:
          - ap-south-1a
          - ap-south-1b
          - ap-south-1c
#NAT Gateway
    - name: aws-nat-gateway
      alias: ngw
      dependencies:
        - name: aws-vpc-subnets
          ref: pub_subnets      
      variables:
      - name : connectivity_type
        value: public   
      - name : _count
        value: 3   
# Subnet for ROSA - Private
    - name: aws-vpc-subnets
      alias: pri_subnets
      dependencies:
        - name: gateways
          ref: ngw
      variables:
      - name: label
        value: private
      - name: subnet_cidrs
        alias: pri_subnets_cidrs
        value:
          - 10.0.4.0/24
          - 10.0.5.0/24
          - 10.0.6.0/24
      - name: availability_zones
        value:
          - ap-south-1a
          - ap-south-1b
          - ap-south-1c
#ROSA 
    - name: aws-rosa
      dependencies:
        - name: public-subnets
          ref: pub_subnets
        - name: private-subnets
          ref: pri_subnets
      variables:
        - name: multi-zone-cluster
          value: true
        - name: no_of_compute_nodes
          value: 3
        - name: dry_run
          value: true
        - name: machine-cidr
          value:  10.0.0.0/16
        - name: service-cidr
          value: 172.30.0.0/16
        - name: pod-cidr
          value: 10.128.0.0/14
        - name: rosa_token          
          important: true
#KMS for encryption
    - name: aws-kms
      variables:
      - name: rotation_enabled
        value: true
      - name : key_spec
        value: SYMMETRIC_DEFAULT
      - name: enabled
        value: true
#SSH Key
    - name: aws-ssh-key
      alias: ec2_access_key
      variables:
      - name: rsa_bits
        value: 3072
      - name: label
        value: swe-key
#EC2 Instance
    - name: aws-ec2-instance
      dependencies:
        - name: aws-vpc
        - name: aws-vpc-subnets
          ref: pri_subnets
#        - name: aws-vpc-subnets
#          ref: pub_subnets
        - name: aws-ssh-key
        - name: aws-kms
      variables:
      - name: instance_type
        value: t3.large
      - name: ami_id
        value: ami-03fa4afc89e4a8a09
      - name: root_block_device_encrypted
        value: true
      - name: root_volume_size
        value: 10
      - name: root_volume_type
        value: gp2
#Bastion Instance
    - name: aws-ec2-bastion
      dependencies:
        - name: aws-vpc
        - name: aws-vpc-subnets
          ref: pub_subnets
        - name: aws-ssh-key
        - name: aws-kms
        - name: aws-ec2-insatnce
      variables:
      - name: instance_type
        value: t3.large
      - name: ami_id
        value: ami-03fa4afc89e4a8a09
      - name: root_block_device_encrypted
        value: true
      - name: root_volume_size
        value: 10
      - name: root_volume_type
        value: gp2
#VPN service
    - name: aws-client-vpn
      dependencies:
        - name: aws-vpc-subnets
          ref: pri_subnets
        - name: aws-vpc
      variables:
      - name: number_subnets_vpn
        value: 3
      - name: client_cidr_block
        value: 172.13.0.0/16
      - name: dns_servers
        value:
          - 10.0.0.2
      - name: allowed_cidr_ranges
        value:
          - 10.0.0.0/16
#Global value    
  variables:
    - name: name_prefix
      scope: global
      value: sw-bom4
    - name: provision
      value: true
      scope: global    
    - name: resource_group_name
    - name: region
      value: ap-south-1
      scope: global              
