apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 250-turbonomic-multicloud
  labels:
    type: software
    code: '250'
  annotations:
    displayName: Turbonomic on OpenShift - Multi Cloud
    description: GitOps deployment of Turbonomic on Multi Cloud environments AWS, Azure and IBM Cloud
spec:
  modules:

    # Create the GitOps Repo
    - name: gitops-repo

    # Create Name Space for Turbonomic
    - name: gitops-namespace
      alias: turbo_namespace
      default: true
      variables:
        - name: name
          value: turbonomic

    # Define Turbonomic GitOps resources for OpenShift GitOps to install
    - name: gitops-ocp-turbonomic

