apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 170-ibm-fs-openshift-gitops
  labels:
    type: infrastructure
    code: '170'
  annotations:
    displayName: OpenShift GitOps (ArgoCD)
    description: Provision GitOps (ArgoCD) on OpenShift
    vpn/required: "true"
    deployment-type/gitops: "true"
spec:
  modules:
    - name: ocp-login
      variables:
        - name: server_url
          required: true
        - name: login_user
          value: apikey
        - name: login_password
          alias: ibmcloud_api_key
          scope: global
    - name: namespace
      alias: tools_namespace
      default: true
      variables:
        - name: name
          value: tools
    - name: cluster-config
      alias: config
      variables:
        - name: banner_text
          value: Workload
        - name: banner_background_color
          value: red
    - name: openshift-cicd
  variables:
    - name: config_banner_text
    - name: tools_name
      value: tools
    - name: sealed-secret_name
      value: sealed-secrets
