apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 120-ibm-zdev-network-vpc-openshift
  labels:
    type: infrastructure
    platform: ibm
    code: 120
  annotations:
    displayName: Network VPC
    description: Network VPC with VPN and Bastion servers
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
    - name: ibm-resource-group
      alias: at_resource_group
    - name: ibm-kms
      alias: kms
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ""
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: zos_resource_group_name
          scope: global
    - name: ibm-iam-service-authorization
      alias: flow-log-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: flow-log-collector
        - name: roles
          value:
            - Writer
      dependencies:
        - name: target_resource_group
          ref:  ibm-resource-group
        - name: target_resource
          ref: cos
    - name: ibm-access-group
    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 1
        - name: address_prefixes
          value:
            - 10.1.0.0/18
            - 10.2.0.0/18
            - 10.3.0.0/18
    - name: ibm-flow-logs
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.1.20.0/24
            - 10.2.20.0/24
            - 10.3.20.0/24
    - name: ibm-vpc-subnets
      alias: ingress-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.10.0/24
            - 10.2.10.0/24
            - 10.3.10.0/24
        - name: acl_rules
          value:
            - {"name":"allow-vpn-ingress","action":"allow","direction":"inbound","source":"0.0.0.0/0", "destination":"10.0.0.0/8"}
            - {"name":"allow-vpn-egress","action":"allow","direction":"inbound","source":"10.0.0.0/8", "destination":"0.0.0.0/0"}
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: worker-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: worker
        - name: ipv4_cidr_blocks
          value:
            - 10.1.30.0/24
            - 10.2.30.0/24
            - 10.3.30.0/24
    - name: ibm-vpc-subnets
      alias: egress-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: egress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.40.0/24
            - 10.2.40.0/24
            - 10.3.40.0/24
    - name: ibm-vpc-vpn-gateway
      dependencies:
        - name: subnets
          ref: ingress-subnets
    - name: ibm-vpn-server
      dependencies:
        - name: subnets
          ref: ingress-subnets
        - name: ibm-secrets-manager
          ref: secrets-manager
    # - name: ibm-vpc-ssh
    #   alias: zos_ssh_bastion
    #   variables:
    #     - name: label
    #       value: bastion
    # - name: vsi-bastion
    #   variables:
    #     - name: image_name
    #       scope: module
    #     - name: kms_enabled
    #       value: true
    #   dependencies:
    #     - name: subnets
    #       ref: bastion-subnets
    #     - name: vpcssh
    #       ref: zos_ssh_bastion
    - name: ibm-resource-group
      alias: zos_resource_group
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: zos_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: zos_resource_group
    - name: ibm-kms-key
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-activity-tracker
      dependencies:
        - name: resource_group
          ref: at_resource_group
    - name: ibm-cloud-monitoring
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: zos_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: zos_resource_group
    - name: ibm-secrets-manager
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: zos_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: zos_resource_group
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    # - name: ibm-transit-gateway
    #   variables:
    #     - name: name_prefix
    #       alias: zos_name_prefix
    #       scope: global
    #   dependencies:
    #     - name: resource-group
    #       ref: zos_resource_group



# this is new


    - name: ibm-vpe-gateway
      alias: vpe-cos
      dependencies:
        - name: resource
          ref: cos
        - name: subnets
          ref: vpe-subnets

#need vars for profile_name and image name?


    - name: ibm-ocp-vpc
      alias: cluster
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
        - name: worker_count
        - name: ocp_version
          value: "4.10"
        - name: cluster_flavor
          value: "bx2.16x64"
      dependencies:
        - name: subnets
          ref: worker-subnets
        - name: kms_key
          ref: kms-key


    - name: ibm-vpc-subnets
      alias: vsi-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: worker-vsi
        - name: ipv4_cidr_blocks
          value:
            - 10.1.50.0/24
            - 10.2.50.0/24
            - 10.3.50.0/24
        - name: acl_rules
          value:
            - {"name":"allow-vpn-ingress","action":"allow","direction":"inbound","source":"0.0.0.0/0", "destination":"10.0.0.0/8"}
            - {"name":"allow-vpn-egress","action":"allow","direction":"inbound","source":"10.0.0.0/8", "destination":"0.0.0.0/0"}
    - name: ibm-vpc-vsi
      variables:
        - name: image_name
          value: "ibm-zos-2-4-s390x-dev-test-wazi-5"
        - name: profile_name
          value: "mz2-2x16"
        - name: security_group_rules
          value:
            - { "name": "ingress-everything", "direction": "inbound", "remote": "0.0.0.0/0"}
            - { "name": "egress-everything", "direction": "outbound", "remote": "0.0.0.0/0" }
      dependencies:
        - name: subnets
          ref: vsi-subnets
        - name: vpcssh
          ref: dev_ssh_vsi
    - name: ibm-vpc-ssh
      alias: dev_ssh_vsi
      variables:
        - name: label
          value: zos-vsi


  variables:
    - name: zos_resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      alias: zos_name_prefix
      required: true
      scope: global
    - name: zos_resource_group_name
    - name: zos_name_prefix
    - name: kms_service
    # # - name: zos_ssh_vpn_public_key
    # #   value: ""
    # # - name: zos_ssh_vpn_private_key
    # #   value: ""
    # - name: zos_ssh_bastion_public_key
    #   value: ""
    # - name: zos_ssh_bastion_private_key
    #   value: ""
    # # - name: zos_ssh_vpn_public_key_file
    # # - name: zos_ssh_vpn_private_key_file
    # - name: zos_ssh_bastion_public_key_file
    # - name: zos_ssh_bastion_private_key_file
