apiVersion: cloudnativetoolkit.dev/v2
kind: Solution
metadata:
  name: devtools-openshift
  labels:
    type: infrastructure
  annotations:
    displayName: "Software: Dev Tools"
    description: Automation to deploy dev tools on OpenShift clusters
spec:
  version: v1.0.0
  stack: 
    - name: 105-existing-openshift
      layer: software
      description: Provisions OpenShift GitOps (ArgoCD) into an existing cluster and bootstraps it to a gitops repository
    - name:  200-gitops-starter-openshift
      layer: software
      description: Provisions OpenShift GitOps (ArgoCD) into an existing cluster and bootstraps it to a gitops repository
    - name: 201-dev-tools
      layer: software
      description: Deploy development tools
