apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-ibm-portworx-storage
  labels:
    type: infrastructure
    platform: ibm
    code: '210'
    storage: portworx
  annotations:
    displayName: IBM - Portworx Cluster Storage
    description: Installs Portworx in an IBM cluster
spec:
  modules:
    - name: ocp-login

    - name: gitops-namespace
      alias: gitea_namespace
      variables:
        - name: name
          value: gitea

    - name: gitea
      dependencies:
        - id: namespace
          ref: gitea_namespace

    - name: gitops-repo
    - name: gitops-namespace
      alias: portworx_namespace
      default: true
      variables:
        - name: name
          value: portworx
    - name: gitops-ibm-portworx
    - name: ibm-resource-group
