apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: gitops-telco-cloud
  labels:
    code: '500'
  annotations:
    displayName: Telco Core
    description: Telco Core on OpenShift
spec:
  # assumes cluster already exists, is this enough for bootstrapping gitops?
  modules:

    # Login into IBM Cloud Clusters setup GitOps
    - name: ocp-login
      alias: cp4i
    - name: gitops-repo
      alias: cp4i-repo
      variables:
        - name: server_name
          value: telco-cp4i
    - name: gitops-bootstrap
      alias: cp4i-gitops
      dependencies:
        - id: cluster
          ref: cp4i
        - id: gitops
          ref: cp4i-repo

    - name: ocp-login
      alias: cp4d
    - name: gitops-repo
      alias: cp4d-repo
      variables:
        - name: server_name
          value: telco-cp4d
    - name: gitops-bootstrap
      alias: cp4d-gitops
      dependencies:
        - id: cluster
          ref: cp4d
        - id: gitops
          ref: cp4d-repo

    # Cloud Pak Base
    - name: gitops-cp-catalogs
      alias: cp4i-catalogs
      dependencies:
        - id: gitops
          ref: cp4i-repo
    - name: gitops-cp-catalogs
      alias: cp4d-catalogs
      dependencies:
        - id: gitops
          ref: cp4d-repo

    - name: gitops-cp-platform-navigator
      dependencies:
        - id: gitops
          ref: cp4i-repo

    # Cloud Pak for Database Base
    - name: gitops-cp4d-operator
      dependencies:
        - id: gitops
          ref: cp4d-repo
    - name: gitops-cp4d-instance
      dependencies:
        - id: gitops
          ref: cp4d-repo

    # IBM Cloud
#    - name: ibm-portworx 
#    - name: gitops-ibm-ocs 

    # DB2 and DB2 Warehouse   
    - name: gitops-db2
      dependencies:
        - id: gitops
          ref: cp4d-repo
    #- name: gitops-cp-db2wh

    # Cloud Pak for Integration
    - name: gitops-console-link-job
    - name: cp4i-dependency-management
#   - name: gitops-namespace
#      variables:
#        - name: name
#          alias: tools
#          value: tools
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic

    # Cloud Pak for Automation
    
# Will be replaced by CP ODM
#  - name: odm 


    # Sterling Manager
#  - name: gitops-cp-sterling-oms



