apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: gitops-telco-cloud-cp4i
  labels:
    type: software
    code: '500'
  annotations:
    displayName: Telco CP4I
    description: Telco CP4I on OpenShift
spec:
  # assumes cluster already exists, is this enough for bootstrapping gitops?
  modules:

    # Login into IBM Cloud Clusters setup GitOps
    - name: ocp-login
    - name: gitops-repo
    - name: gitops-bootstrap

    # Cloud Pak Base
    - name: gitops-cp-catalogs
    - name: gitops-cp-platform-navigator
    
    # IBM Cloud
#    - name: ibm-portworx 
#    - name: gitops-ibm-ocs 

    # Cloud Pak for Integration
    - name: gitops-console-link-job
    - name: cp4i-dependency-management
#   - name: gitops-namespace
#      variables:
#        - name: name
#          alias: tools
#          value: tools
    - name: gitops-cp-mq
    - name: gitops-cp-queue-manager


    # Cloud Pak for Automation
    
# Will be replaced by CP ODM
#  - name: odm 


    # Sterling Manager
#  - name: gitops-cp-sterling-oms



