apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: gitops-telco-cloud-cp4ba
  labels:
    code: '500'
  annotations:
    displayName: Telco Core
    description: Telco Core on OpenShift
spec:
  # assumes cluster already exists, is this enough for bootstrapping gitops?
  modules:

    # Login into IBM Cloud Clusters setup GitOps
    - name: ocp-login
    - name: gitops-repo
    - name: gitops-bootstrap

    # Cloud Pak Base
    - name: gitops-cp-catalogs
    - name: gitops-cp-platform-navigator

    # Cloud Pak for Integration
    - name: gitops-console-link-job
    - name: cp4i-dependency-management
#   - name: gitops-namespace
#      variables:
#        - name: name
#          alias: tools
#          value: tools
    - name: gitops-cp-mq
    - name: gitops-cp-queue-manager




