apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 100-aws-ec2-insatnce
  labels:
    platform: aws
    code: '100'
  annotations:
    displayName: AWS EC2 Instance
    description: EC2 instance in VPC in AWS
spec:
  modules:
    - name: aws-vpc
      alias: test-vpc
      # variables:
      # - name: provision
      #   value: false
      variables:
      - name: provision
      - name: internal_cidr          
      - name: instance_tenancy
      - name: name_prefix
    - name: aws-vpc-subnets
      alias: pub-subnet
      dependencies:
        - name: aws-vpc
          ref: test-vpc
      variables:
      - name: vpc_id
      - name: private_subnet_cidr
      - name: public_subnet_cidr
      - name: availability_zones
    - name: aws-ssh-key
      alias: ec2-ssh-key
      variables:
      - name: private_key_file
      - name: private_key
      - name: public_key_file
      - name: public_key
      - name: rsa_bits
      - name: prefix_name
      - name: name
      - name: label
      - name: name_prefix 
    - name: aws-kms
      alias: ec2-kms
      variables:
      - name: key_spec
      - name: rotation_enabled
      - name: enabled
      - name: alias
      - name: kms_alias
    - name: aws-ec2-insatnce
      alias: test-ec2instances
      dependencies:
        - name: aws-vpc
          ref: test-vpc
        - name: aws-vpc-subnets
          ref: pub-subnet
        - name: aws-ssh-key
          ref: ec2-ssh-key
        - name: aws-kms
          ref: ec2-kms
      variables:
      - name: vpc_id     
      - name: subnet_ids_pri
      - name: subnet_ids_pub
      - name: ami_id
      - name: subnet_count_private
      - name: subnet_count_public
      - name: instance_type
      - name: publickey
      - name: root_block_device_encrypted
      - name: root_volume_size
      - name: root_volume_type
      - name: publicIP
      - name: ssh_key
      - name: kms_key_id
  variables:
    - name: name_prefix
      alias: common_name_prefix
    - name: region
