apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 100-ibm-shared-services
  labels:
    type: infrastructure
    platform: ibm
    code: '100'
  annotations:
    displayName: IBM Shared services
    description: Managed services that are shared across the networks
spec:
  modules:
    - name: ibm-resource-group
      alias: cs_resource_group
      default: true
    - name: ibm-resource-group
      alias: kms_resource_group
      dependencies:
        - name: sync
          ref: cs_resource_group
    - name: ibm-kms
      alias: kms
      variables:
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
        - name: name
          required: true
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-object-storage
    - name: ibm-cloud-monitoring
    - name: ibm-activity-tracker
    - name: ibm-log-analysis
    - name: ibm-iam-service-authorization
      alias: vsi-encrypt-auth
      variables:
        - name: source_service_name
          value: server-protect
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
    - name: ibm-iam-service-authorization
      alias: cos-encrypt-auth
      variables:
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
        - name: source_resource
          ref: cos
    - name: ibm-iam-service-authorization
      alias: flow-log-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: flow-log-collector
        - name: roles
          value:
            - Writer
      dependencies:
        - name: target_resource_group
          ref: cs_resource_group
        - name: target_resource
          ref: cos
    - name: ibm-iam-service-authorization
      alias: vsi-encrypt-auth
      variables:
        - name: source_service_name
          value: server-protect
        - name: roles
          value:
            - Reader
      dependencies:
        - name: source_resource_group
          ref: cs_resource_group
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
    - name: ibm-iam-service-authorization
      alias: kube-encrypt-auth
      variables:
        - name: source_service_name
          value: containers-kubernetes
        - name: roles
          value:
            - Reader
      dependencies:
        - name: source_resource_group
          ref: cs_resource_group
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
    - name: ibm-cert-manager
      variables:
        - name: private_endpoint
          value: false
    - name: ibm-iam-service-authorization
      alias: vpn-cert-manager-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: vpn-server
        - name: roles
          value:
            - Writer
        - name: target_service_name
          value: cloudcerts
  variables:
    - name: name_prefix
      alias: cs_name_prefix
    - name: region
    - name: kms_service
