apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-aws-portworx-storage
  labels:
    type: infrastructure
    code: '210'
    platform: aws
    storage: portworx
  annotations:
    displayName: AWS - Portworx Cluster Storage
    description: Installs Portworx in and OCP cluster on AWS
spec:
  modules:
    - name: aws-portworx

