apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-aws-portworx-storage
  labels:
    type: infrastructure
    code: '210'
    platform: aws
    storage: portworx
  annotations:
    displayName: AWS - Portworx Cluster Storage
    description: Installs Portworx in and OCP cluster on AWS
spec:
  modules:
    - name: aws-portworx

      variables: 
      - name: region
        scope: global
      - name: access_key
        scope: global
      - name: secret_key
        scope: global
      - name: portworx_spec_file
        scope: global
      - name: portworx_spec
        scope: global      
        important: true        


