apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-ibm-portworx-storage
  labels:
    type: infrastructure
    platform: ibm
    code: '210'
  annotations:
    displayName: IBM - Portworx Cluster Storage
    description: Installs Portworx in an IBM cluster
spec:
  modules:
    - name: ibm-portworx
      variables:
        - name: etcd_secret_name
          optional: true
          value: "px-etcd-certs"
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
    - name: ibm-vpc
      variables:
        - name: provision
          value: false
    - name: ibm-vpc-subnets
      default: true
      alias: cluster_subnets
      variables:
        - name: provision
          value: false
    - name: ibm-ocp-vpc
      dependencies:
        - name: cos
          optional: true
      variables:
        - name: exists
          value: true
        - name: name
          important: true
          description: "The cluster where Portworx storage will be deployed."
        - name: flavor
          important: false
          optional: true
          value: ""
        - name: vpc_name
          value: ""
          important: false
          optional: true
        - name: cos_id
          important: false
          optional: true
          value: ""
        - name: worker_count
          important: false
          optional: true

