apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 260-integration-mq-uniform-cluster
  labels:
    type: software
    code: '260'
  annotations:
    displayName: Integration Platform
    description: Populates a GitOps repository with IBM MQ Uniform Cluster components of the IBM Integration Platform
spec:
  modules:
    # Login to existing OpenShift cluster
    - name: ocp-login
      alias: cluster
      version: v1.2.12
    - name: olm
      version: v1.3.2
    - name: sealed-secret-cert
      version: v1.0.1
    
    - name: gitops-repo
      alias: gitops_repo
      version: v1.16.0

    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.1
      variables:
        - name: entitlement_key
          scope: global

    # # MQ Operators
    - name: gitops-cp-mq


    # To organize the MQ Uniform cluster Workload in a dedicated namespace. Also to Override the Storage Class for MQ Uniform cluster. Require RWO storage Class
    - name: gitops-namespace
      alias: cp4i-mq-cluster
      variables:
        - name: name
          value: cp4i-mq-cluster

    - name: gitops-cp-mq-uniform-cluster
      dependencies:
        - name: namespace
          ref: cp4i-mq-cluster
      variables:
        - name: storageClass
          alias: rwo_storage_class
          scope: global


  variables:
    - name: rwo_storage_class
      type: string
      description: ReadWriteOnce access type Storage Class
    
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true  
    - name: gitops_repo_host
      type: string
      description: The host for the git repository.
    - name: gitops_repo_type
      type: string
      description: The type of the hosted git repository (github or gitlab).
    - name: gitops_repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      sensitive: true
    - name: gitops-cluster-config_banner_text
      type: string
      description: The text that will appear in the top banner in the cluster
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
    




