apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 280-integration-platform-multicloud
  labels:
    type: software
    code: '280'
  annotations:
    displayName: Integration Platform
    description: Populates a GitOps repository with the components of the IBM Integration Platform
spec:
  modules:
    # Login to existing OpenShift cluster
    - name: ocp-login
      alias: cluster
      version: v1.2.12
    - name: olm
      version: v1.3.2
    - name: sealed-secret-cert
      version: v1.0.1

    - name: gitops-repo
      alias: gitops_repo
      version: v1.16.0

    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.1
      variables:
        - name: entitlement_key
          scope: global

    # # CP4i Operators
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic-opearator
    - name: gitops-cp-eventstreams


    # To organize the MQ Uniform cluster Workload in a dedicated namespace. Also to Override the Storage Class for MQ Uniform cluster. Require RWO storage Class
    - name: gitops-namespace
      alias: cp4i-mq-cluster
      variables:
        - name: name
          value: cp4i-mq-cluster

    - name: gitops-cp-mq-uniform-cluster
      dependencies:
        - name: namespace
          ref: cp4i-mq-cluster
      variables:
        - name: storageClass
          alias: rwo_storage_class
          scope: global

    # To organize the AppConnect Enterprise Workload in a dedicated namespace. Also to Override the Storage Class for ACEDesigner. Require RWO & RWX storage Class
    - name: gitops-namespace
      alias: cp4i-ace
      variables:
        - name: name
          value: cp4i-ace

    - name: gitops-cp-ace-designer
      dependencies:
        - name: namespace
          ref: cp4i-ace
      variables:
        - name: storage_class_4_couchdb
          alias: rwo_storage_class
          scope: global
        - name: storage_class_4_mapassist
          alias: rwx_storage_class
          scope: global
        # If MapAssist feature is required. Then set the 'value' to 'true'
        - name: is_map_assist_required
          value: false

    # To organize the QueueManager Workload in a dedicated namespace. Also to Override the Storage Class for QueueManager. Require RWO storage Class
    - name: gitops-namespace
      alias: cp4i-mq
      variables:
        - name: name
          value: cp4i-mq

    - name: gitops-cp-queue-manager
      dependencies:
        - name: namespace
          ref: cp4i-mq
      variables:
        - name: qmgr_name
          value: QM1
        - name: qmgr_instance_name
          value: mq-instance
        - name: config_map
          value: oms-queue-config
        - name: storageclass
          alias: rwo_storage_class
          scope: global

    # To organize the APIConnect Workload in a dedicated namespace. Also to Override the Storage Class for APIConnect. Require RWO storage Class
    - name: gitops-namespace
      alias: cp4i-apic
      variables:
        - name: name
          value: cp4i-apic

    - name: gitops-cp-apic
      dependencies:
        - name: namespace
          ref: cp4i-apic
      variables:
        - name: storage_class
          alias: rwo_storage_class
          scope: global
        - name: entitlement_key
          scope: global

    # To organize the PlatformNavigator Workload in a dedicated namespace. Also to Override the Storage Class for PlatformNavigator. Require RWX storage Class
    - name: gitops-namespace
      alias: cp4i-pn
      variables:
        - name: name
          value: cp4i-pn

    - name: gitops-cp-platform-navigator
      dependencies:
        - name: namespace
          ref: cp4i-pn
      variables:
        - name: storageclass
          alias: rwx_storage_class
          scope: global


  variables:
    #This storageclass is reffered by[ACE Designer/MQ UniformCluster/MQ]
    - name: rwo_storage_class
      type: string
      description: ReadWriteOnce access type Storage Class

    #This storageclass is reffered by[PlatforNavigator/ACEDesigner]
    - name: rwx_storage_class
      type: string
      description: ReadWriteMany access type Storage Class

    #For EntitlementKey is reffered by [PlatformNavigator/MQ Uniform Cluster/ACE Designer/APIC/MQ/EventStreams]
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true
    - name: gitops_repo_host
      type: string
      description: The host for the git repository.
    - name: gitops_repo_type
      type: string
      description: The type of the hosted git repository (github or gitlab).
    - name: gitops_repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      sensitive: true
    - name: gitops-cluster-config_banner_text
      type: string
      description: The text that will appear in the top banner in the cluster
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
