apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 300-cp-integration
  labels:
    code: '300'
  annotations:
    displayName: Cloud Pak for Integration
    description: GitOps deployment of Cloud Pak for Integration on OpenShift
spec:
  modules:
    - name: ocp-login
    - name: argocd-bootstrap
    - name: gitops-console-link-job
    - name: gitops-namespace
      variables:
        - name: name
          alias: tools
          value: tools
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic
    - name: gitops-cp-eventstreams