apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 300-integration-platform-multicloud
  labels:
    type: software
    code: '300'
  annotations:
    displayName: Integration Platform
    description: Populates a GitOps repository with the components of the IBM Integration Platform
spec:
  modules:
    - name: gitops-repo
    - name: gitops-cp-catalogs

    # # CP4i Operators
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic-opearator
    - name: gitops-cp-eventstreams

    # To create dedicated namespace for PN, MQ , Uniform-Cluster,ACE-Designer
    - name: gitops-namespace
      alias: cp4i
      variables:
        - name: name
          value: cp4i

    # To Override the Storage Class for PlatformNavigator. Require RWX storage Class
    - name: gitops-namespace
      alias: cp4i-pn
      variables:
        - name: name
          value: cp4i-pn

    - name: gitops-cp-platform-navigator
      dependencies:
        - name: namespace
          ref: cp4i-pn
      variables:
        - name: storageclass
          alias: rwx_storage_class
          scope: global

    # To Override the Storage Class for MQ Uniform cluster
    - name: gitops-namespace
      alias: cp4i-mq-cluster
      variables:
        - name: name
          value: cp4i-mq-cluster

    - name: gitops-cp-mq-uniform-cluster
      dependencies:
        - name: namespace
          ref: cp4i-mq-cluster
      variables:
        - name: storageclass
          alias: rwo_storage_class
          scope: global

    # To Override the Storage Class for ACE Designer. Require RWX storage Class if we enable MapAssist feature
    - name: gitops-namespace
      alias: cp4i-ace
      variables:
        - name: name
          value: cp4i-ace

    - name: gitops-cp-ace-designer
      dependencies:
        - name: namespace
          ref: cp4i-ace
      variables:
        - name: storage_class_4_couchdb
          alias: rwo_storage_class
          scope: global
        - name: storage_class_4_mapassist
          alias: rwx_storage_class
          scope: global
        - name: is_map_assist_required
          value: false

    # To Override the Storage Class for MQ Queue Manager Instance
    - name: gitops-namespace
      alias: cp4i-mq
      variables:
        - name: name
          value: cp4i-mq

    - name: gitops-cp-queue-manager
      dependencies:
        - name: namespace
          ref: cp4i-mq
      variables:
        - name: qmgr_name
          value: QM1
        - name: qmgr_instance_name
          value: telco-cloud
        - name: config_map
          value: oms-queue-config
        - name: storageclass
          alias: rwo_storage_class
          scope: global

    # To Override the Storage Class for APIC  Instance
    - name: gitops-namespace
      alias: cp4i-apic
      variables:
        - name: name
          value: cp4i-apic

    - name: gitops-cp-apic
      dependencies:
        - name: namespace
          ref: cp4i-apic
      variables:
        - name: storage_class
          alias: rwo_storage_class
          scope: global
