apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 304-cp-integration
  labels:
    code: '300'
  annotations:
    displayName: Cloud Pak for Integration
    description: GitOps deployment of Cloud Pak for Integration on OpenShift  
spec:
  modules:
    - name: ocp-login
    - name: gitops-cp-catalogs
    - name: olm
    - name: sealed-secret-cert
    - name: gitops-repo
    - name: argocd-bootstrap
    - name: gitops-console-link-job

    
    # # CP4i Operators
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic-opearator
    - name: gitops-cp-eventstreams

    # To create dedicated namespace for PN, MQ , Uniform-Cluster,ACE-Designer
    - name: gitops-namespace  
      variables:
        - name: name
          value: gitops-cp4i 
        - name: name
          value: cp4i-pn    
        - name: name
          value: cp4i-mq    
        - name: name
          value: cp4i-ace    
        - name: name
          value: cp4i-apic    

    # To Override the Storage Class for PlatformNavigator
    - name: gitops-cp-platform-navigator
      dependencies:
        - name: namespace
          ref: cp4i-pn    
      variables:
        - name: storageclass
          value: portworx-rwx-gp-sc   
 

    # To Override the Storage Class for MQ Uniform cluster
    - name: gitops-cp-mq-uniform-cluster
      dependencies:
        - name: namespace
          ref: cp4i-mq-cluster
      variables:
        - name: storageclass
          value: portworx-db2-rwo-sc

    # To Override the Storage Class for ACE Designer
    - name: gitops-cp-ace-designer
      dependencies:
        - name: namespace
          ref: cp4i-ace    
      variables:
        - name: storage_class_4_couchdb
          value: portworx-db2-rwo-sc
        - name: storage_class_4_mapassist
          value: portworx-rwx-gp-sc
        - name: is_map_assist_required
          value: false

    # To Override the Storage Class for MQ Queue Manager Instance
    - name: gitops-cp-queue-manager
      dependencies:
        - name: namespace
          ref: cp4i-mq    
      variables:
        - name: qmgr_name
          value: QM1
        - name: qmgr_instance_name
          value: telco-cloud
        - name: config_map
          value: oms-queue-config

    # # To Override the Storage Class for APIC  Instance
    # # The Current status of this module is : NOT RELEASED. Hence commented out
    # - name: gitops-cp-apic
    #   dependencies:
    #     - name: namespace
    #       ref: cp4i-apic    
    #   variables:
    #     - name: storage_class_name
    #       value: portworx-db2-rwo-sc
