apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 400-gitops-cp-maximo
  labels:
    code: '400'
  annotations:
    displayName: Maximo Application Suite
    description: GitOps deployment of Maximo for OpenShift
spec:
  modules:
    - name: gitops-repo
      alias: gitops-repo
      version: v1.15.1
    - name: gitops-bootstrap
      alias: gitops-bootstrap
      version: v1.2.9
    - name: gitops-cp-bas
      alias: bas
      version: v1.0.1
      dependencies:
        - name: namespace
          ref: bas-namespace
    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.1
      variables:
        - name: entitlement_key
          scope: global
    - name: gitops-cp-maximo
      alias: gitops-cp-maximo
      version: v1.0.5
      variables:
        - name: instanceid
          ref: mas8
        - name: cluster_ingress
          scope: global
        - name: entitlement_key
          scope: global
    - name: gitops-cp-sls
      alias: sls
      version: v2.2.1
      dependencies:
        - name: namespace
          ref: sls-namespace
      variables:
        - name: cluster_ingress
          scope: global
        - name: entitlement_key
          scope: global
    - name: gitops-mongo-ce-operator
      alias: gitops-mongo-ce-operator
      version: v1.0.4
      dependencies:
        - name: namespace
          ref: mongo-namespace
    - name: gitops-mongo-ce
      alias: gitops-mongo-ce
      version: v1.1.3
      dependencies:
        - name: namespace
          ref: mongo-namespace
    - name: gitops-namespace
      alias: sls-namespace
      version: v1.11.1
    - name: gitops-namespace
      alias: mongo-namespace
      version: v1.11.1
    - name: gitops-namespace
      alias: bas-namespace
      version: v1.11.1
    - name: ocp-login
      alias: cluster
      version: v1.2.8
    - name: sealed-secret-cert
      version: v1.0.0
    - name: util-clis
      version: v1.8.5
  variables:
    - name: gitops-repo_host
      type: string
      description: The host for the git repository.
    - name: gitops-repo_type
      type: string
      description: The type of the hosted git repository (github or gitlab).
    - name: gitops-repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
    - name: gitops-repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: gitops-repo_username
      type: string
      description: The username of the user with access to the repository
    - name: gitops-repo_token
      type: string
      description: The personal access token used to access the repository
      sensitive: true
    - name: bas_dbpassword
      type: string
      description: The (mongodb) database password
      sensitive: true
    - name: bas_grafanapassword
      type: string
      description: The grafana password
      sensitive: true
    - name: bas_default_storage_class
      type: string
      description: The default storage class for the resources
    - name: bas_db_archive_storage_class
      type: string
      description: Storage class for the db_archive resource
    - name: bas_postgres_storage_class
      type: string
      description: Storage class for the postgres resource
    - name: bas_kafka_storage_class
      type: string
      description: Storage class for the kafka resource
    - name: bas_zookeeper_storage_class
      type: string
      description: Storage class for the zookeeper resource
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true
    - name: cluster_ingress
      type: string
      description: Ingress for cluster
    - name: gitops-cp-maximo_instanceid
      type: string
      description: 'instance name for MAS - for example: masdemo or mas8 '
    - name: gitops-mongo-ce-operator_mongo_storageclass
      type: string
      description: Storageclass for MongoDB
    - name: gitops-mongo-ce_storage_class_name
      type: string
      description: The storage class to use for database
    - name: sls-namespace_name
      type: string
      description: The value that should be used for the namespace
    - name: mongo-namespace_name
      type: string
      description: The value that should be used for the namespace
    - name: bas-namespace_name
      type: string
      description: The value that should be used for the namespace
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
