apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 405-mas-manage
  labels:
    type: software
    code: '405'
  annotations:
    displayName: Maximo Application Suite - Manage Application
    description: GitOps deployment of Maximo Manage application for OpenShift
    deployment-type/gitops: "true"
spec:
  version: v2.0.0
  modules:
    - name: gitops-repo
    - name: util-mas-core-existing
    # Maximo Application Suite - Manage
    - name: gitops-mas-manage
